# * Esto es para ver las consultas, sin postman.

### Recuperar todos los datos
GET http://localhost:3000

### Obtener todas las películas
GET http://localhost:3000/movies

### Obtener película por id
GET http://localhost:3000/movies/166a7ef9-7ba3-11f0-9ace-00090faa0001

### Obtener película por género
# GET http://localhost:3000/movies?genre=thriller
GET http://localhost:3000/movies?genre=ACTION

### Crear una película - gracias a zod no se genera el "sql"
POST http://localhost:3000/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM users",
    "title": "Prueba nueva",
    "year": 1999,
    "director": "Daniel Myrick",
    "duration": 81,
    "poster": "https://image.tmdb.org/t/p/blairwitch.jpg",
    "rate": 7.8,
    "genre": ["Horror", "Mystery", "Action"]
}

### Actualizar una película
PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
    "id": "123123",
    "title": 123
}

